name: CI/CD Pipeline
on:
  pull_request:
  push:
    branches:
      # - 'master'
      - 'main'
      - 'dev/**'
      - 'develop/**'

jobs:
  setup:
    # env:
    #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_SAPEET_DEV }}
    #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_SAPEET_DEV }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-testandlint-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: ${{ runner.os }}-testandlint-
      - name: Install packages
        run: yarn install
      - name: Lint
        run: yarn lint:ci
      # - name: Test
      #   run: yarn test
      - name: Build
        run: yarn build:prod
      # - name: Deploy toppan-alpha
      #   if: github.ref == 'refs/heads/master'
      #   run: aws codebuild start-build --region ap-northeast-1 --project-name shisei-karte-client-toppan-alpha
